<?php
declare(strict_types=1);

const ALLOWED_ORIGIN = 'https://annaraksha.unbeatablefoods.com';

function send_cors_headers(): void {
    $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
    if ($origin === ALLOWED_ORIGIN) { header('Access-Control-Allow-Origin: '.ALLOWED_ORIGIN); header('Vary: Origin'); }
    header('Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Accept, Authorization');
    header('Access-Control-Max-Age: 86400');
}
function api_init(): void {
    send_cors_headers();
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') { http_response_code(204); exit; }
    header('Content-Type: application/json; charset=utf-8');
}
function api_json($value, int $status = 200): never {
    http_response_code($status); echo json_encode($value, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); exit;
}
function json_error(string $message, int $status = 500): never {
    api_json(['status' => 'error', 'message' => $message], $status);
}
function api_body(): array {
    $raw = file_get_contents('php://input') ?: '';
    $data = json_decode($raw, true);
    return is_array($data) ? $data : ($_POST ?: []);
}
function db(): PDO {
    static $db;
    if ($db instanceof PDO) return $db;
    $db = new PDO('sqlite:'.dirname(__DIR__).'/data/annaraksha.db', null, null, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
    ]);
    $db->exec("CREATE TABLE IF NOT EXISTS storage_units (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,state TEXT NOT NULL,city TEXT NOT NULL,lat REAL NOT NULL,lng REAL NOT NULL,grain_type TEXT NOT NULL,capacity_tonnes INTEGER NOT NULL,current_stock_tonnes INTEGER NOT NULL,moisture_pct REAL NOT NULL,risk_level TEXT NOT NULL DEFAULT 'healthy',predicted_spoilage_date TEXT,last_updated TEXT DEFAULT CURRENT_TIMESTAMP)");
    $db->exec("CREATE TABLE IF NOT EXISTS alerts (id INTEGER PRIMARY KEY AUTOINCREMENT,unit_id INTEGER NOT NULL,message TEXT NOT NULL,severity TEXT NOT NULL,tonnes_at_risk INTEGER NOT NULL,rupees_at_risk REAL NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)");
    try { $db->exec("ALTER TABLE storage_units ADD COLUMN stock_arrival_date TEXT"); } catch (Throwable $e) {}
    return $db;
}
function unit_row($id) { $s=db()->prepare('SELECT * FROM storage_units WHERE id=?'); $s->execute([$id]); return $s->fetch() ?: null; }
function unit_out(array $u): array {
    $arrival = $u['stock_arrival_date'] ?: '2026-08-15';
    $days = max(1, (int)round((strtotime('2026-09-17')-strtotime($arrival))/86400));
    foreach (['id','capacity_tonnes','current_stock_tonnes'] as $k) $u[$k]=(int)$u[$k];
    foreach (['lat','lng','moisture_pct'] as $k) $u[$k]=(float)$u[$k];
    $u['stock_arrival_date']=$arrival; $u['days_in_storage']=$days; return $u;
}
function static_response(string $name): array {
    $now=date('c');
    $impact=['headline_metrics'=>['tonnes_grain_saved'=>48250,'tonnes_grain_saved_display'=>'48,250 MT','capital_value_saved_crores'=>118.60,'capital_value_saved_display'=>'₹118.60 Cr','co2e_footprint_averted_mt'=>43425,'co2e_footprint_display'=>'43,425 MT CO₂e','water_conserved_million_liters'=>57900,'water_conserved_display'=>'57.9 Billion Liters','households_nourished_year'=>321600,'households_nourished_display'=>'321,600 Families'],'efficiency_benchmarks'=>['conventional_spoilage_rate_pct'=>8.5,'annaraksha_monitored_spoilage_pct'=>.38,'loss_reduction_pct'=>95.5,'payback_period_months'=>4.2],'monthly_averted_trend'=>[['month'=>'Jan','tonnes_saved'=>3200,'inr_crores'=>7.8,'co2_mt'=>2880],['month'=>'Feb','tonnes_saved'=>3950,'inr_crores'=>9.6,'co2_mt'=>3550],['month'=>'Mar','tonnes_saved'=>5400,'inr_crores'=>13.2,'co2_mt'=>4860],['month'=>'Apr','tonnes_saved'=>8200,'inr_crores'=>20.1,'co2_mt'=>7380],['month'=>'May','tonnes_saved'=>7800,'inr_crores'=>19.2,'co2_mt'=>7020],['month'=>'Jun','tonnes_saved'=>6900,'inr_crores'=>17,'co2_mt'=>6210],['month'=>'Jul','tonnes_saved'=>6100,'inr_crores'=>15.1,'co2_mt'=>5490],['month'=>'Aug','tonnes_saved'=>6700,'inr_crores'=>16.6,'co2_mt'=>6030]],'sdg_alignment'=>[['sdg'=>'SDG 2: Zero Hunger','contribution'=>'Safeguards 48k+ tonnes staple grains entering food basket instead of rotting'],['sdg'=>'SDG 12: Responsible Consumption','contribution'=>'Target 12.3: Halving per-capita post-harvest food waste along supply chain'],['sdg'=>'SDG 13: Climate Action','contribution'=>'Prevents methane & nitrous oxide emissions from rotting decomposing organic grain mass']]];
    if ($name==='impact') return ['status'=>'success','timestamp'=>$now,'data'=>$impact];
    if ($name==='workorders') return [['order_id'=>'WO-7801-AER','unit_id'=>28,'facility_name'=>'Akola Central Pulses Silo','location'=>'Akola, Maharashtra','crop'=>'Chana','type'=>'Forced Convective Aeration','trigger_reason'=>'Core Biocenter thermal respiration at 34.8°C with 16.8% moisture pocket.','target_parameter'=>'Reduce core temp to 24°C; moisture below 13.0%','fan_sequence'=>'3x 15kW Centrifugal fans run 02:00-07:00 IST (low ambient RH window)','estimated_recovery'=>'₹48.2 Lakhs inventory preserved','status'=>'IN_PROGRESS','progress_pct'=>64,'created_at'=>'1 hour ago'],['order_id'=>'WO-7802-FUM','unit_id'=>4,'facility_name'=>'Amritsar Border Grain Reserve','location'=>'Amritsar, Punjab','crop'=>'Wheat','type'=>'Phosphine Hermetic Fumigation','trigger_reason'=>'Sitophilus granarius infestation detected at 14 weevils/kg in bay 4.','target_parameter'=>'100% insect mortality; sealed tarpaulin dosage 1.5g/m³ for 7 days','fan_sequence'=>'Damper auto-shut, recirculatory fumigation loop active','estimated_recovery'=>'₹1.85 Crores buffer stock safeguarded','status'=>'DISPATCHED','progress_pct'=>30,'created_at'=>'2 hours ago'],['order_id'=>'WO-7803-TRN','unit_id'=>19,'facility_name'=>'Indore Malwa Agro-Silo Hub','location'=>'Indore, Madhya Pradesh','crop'=>'Wheat','type'=>'Mechanical Grain Turning & De-crusting','trigger_reason'=>'Surface crusting layer (15.2% moisture) from diurnal roof condensation.','target_parameter'=>'Turn top 2.5m layer into aeration bin #2','fan_sequence'=>'Conveyor elevator belt active (120 T/hour transfer rate)','estimated_recovery'=>'₹62.5 Lakhs wheat degradation averted','status'=>'TRIGGERED','progress_pct'=>15,'created_at'=>'3 hours ago']];
    if ($name==='logistics') return ['status'=>'success','timestamp'=>$now,'data'=>['active_convoys'=>[['truck_id'=>'PB-02-CC-8910','carrier'=>'Kisan Logistics Express','cargo'=>'32.5 Tonnes Durum Wheat','origin'=>'Amritsar Silo Hub #4','destination'=>'Ludhiana Flour Mill Cluster','route'=>'NH-44 Bypass','eta'=>'1 hr 15 mins','weather_risk'=>'CLEAR_TRANSIT','weighbridge_status'=>'PASSED (0.08% tare delta - Nominal)','humidity_protection'=>'Waterproof 650 GSM Tarpaulin Sensor Verified','status'=>'IN_TRANSIT'],['truck_id'=>'MP-09-GF-4122','carrier'=>'Malwa Agro-Transporters','cargo'=>'28.0 Tonnes Sharbati Wheat','origin'=>'Indore Malwa Agro-Silo #19','destination'=>'Bhopal Central Food Hub','route'=>'SH-18 → Rerouted to NH-86 (Avoiding heavy rain cloudburst)','eta'=>'2 hrs 40 mins','weather_risk'=>'WEATHER_REROUTED','weighbridge_status'=>'PASSED (Gate OCR Verified: 41,200 kg Gross)','humidity_protection'=>'Internal sensor: 12.8% RH stable','status'=>'REROUTED_SAFE'],['truck_id'=>'MH-30-BB-7721','carrier'=>'Vidarbha Heavy Haulers','cargo'=>'30.2 Tonnes Desi Chana','origin'=>'Akola Pulses Silo #28','destination'=>'Nagpur Processing Yard','route'=>'NH-53 East Corridor','eta'=>'3 hrs 10 mins','weather_risk'=>'ORANGE_PRECIPITATION_AHEAD','weighbridge_status'=>'⚠️ ALERT: -340 kg discrepancy detected at Toll Gate 3 weighbridge (Pilferage Check Dispatched)','humidity_protection'=>'High moisture risk: Warning sent to driver','status'=>'UNDER_INSPECTION']]]];
    if ($name==='valuechain') return ['status'=>'success','timestamp'=>$now,'data'=>['at_risk_routing_queue'=>[['lot_id'=>'LOT-MP-1049','origin_unit'=>'Unit #19 - Indore Malwa Agro-Silo','crop'=>'Wheat (15.4% Moisture, 3 Days DTS)','volume_tonnes'=>850,'current_value'=>'₹1.93 Cr','optimal_route'=>'Immediate High-Extraction Whole Wheat Atta','conversion_rationale'=>'Grain moisture (15.4%) eliminates pre-milling conditioning tempering time. Milling immediately preserves gluten index with 0% post-harvest loss.','matched_processor'=>['name'=>'Indore Roller Flour Mills Ltd','distance_km'=>22.4,'transit_hours'=>.8,'spare_daily_capacity_t'=>450,'procurement_bid_per_qtl'=>'₹2,680','gross_recovery_inr'=>'₹2,27,80,000','net_profit_margin_gain'=>'+₹34.8 Lakhs vs distressed salvage'],'buyer_lead'=>'ITC Aashirvaad Chakki Atta Supply Chain','dispatch_status'=>'ROUTE_CLEARED'],['lot_id'=>'LOT-MH-2891','origin_unit'=>'Unit #28 - Akola Central Pulses Silo','crop'=>'Chana / Desi Chickpeas (16.8% Moisture, 2 Days DTS)','volume_tonnes'=>420,'current_value'=>'₹2.28 Cr','optimal_route'=>'Split Dal Desi Besan & Roasted Chana Flakes','conversion_rationale'=>'Immediate de-husking and split dal processing neutralizes microbial surface spore risk, yielding premium commercial besan powder.','matched_processor'=>['name'=>'Vidarbha Pulses & Dal Processing Cluster','distance_km'=>14.8,'transit_hours'=>.5,'spare_daily_capacity_t'=>280,'procurement_bid_per_qtl'=>'₹5,350','gross_recovery_inr'=>'₹2,24,70,000','net_profit_margin_gain'=>'+₹42.0 Lakhs vs spoilage writeoff'],'buyer_lead'=>'Haldiram Foods Agro-Procurement Desk','dispatch_status'=>'PENDING_TRUCK_ALLOCATION']]]];
    if ($name==='ingestion') return ['status'=>'success','timestamp'=>$now,'data'=>['feed_status'=>['agmarknet'=>['status'=>'LIVE_SYNC','ping_ms'=>48,'records_synced'=>4820,'last_sync'=>'2 mins ago'],'imd_radar'=>['status'=>'LIVE_SYNC','ping_ms'=>62,'active_alerts'=>14,'last_sync'=>'4 mins ago'],'fci_cwc'=>['status'=>'LIVE_SYNC','ping_ms'=>112,'depots_monitored'=>2180,'last_sync'=>'12 mins ago'],'isro_sentinel2'=>['status'=>'ORBITAL_PASS','ping_ms'=>210,'coverage_pct'=>94.6,'last_sync'=>'1 hour ago']],'national_inventory_visibility'=>['total_grain_stock_tonnes'=>54890200,'total_valuation_crores'=>134250.80,'breakdown_by_channel'=>['fci_cwc_central_godowns'=>['tonnes'=>31200000,'pct'=>56.8,'units'=>840],'state_civil_supplies'=>['tonnes'=>12450000,'pct'=>22.7,'units'=>620],'apmc_mandis_transit'=>['tonnes'=>4890200,'pct'=>8.9,'units'=>410],'private_warehouses_silos'=>['tonnes'=>6350000,'pct'=>11.6,'units'=>310]],'demand_supply_index'=>['wheat'=>['supply_mt'=>26.4,'demand_mt'=>24.1,'balance'=>'+2.3 MT (Surplus)','trend'=>'stable'],'rice'=>['supply_mt'=>22.1,'demand_mt'=>21,'balance'=>'+1.1 MT (Surplus)','trend'=>'stable'],'chana'=>['supply_mt'=>2.8,'demand_mt'=>3.1,'balance'=>'-0.3 MT (Deficit/Tight)','trend'=>'bullish'],'bajra'=>['supply_mt'=>1.9,'demand_mt'=>1.8,'balance'=>'+0.1 MT (Balanced)','trend'=>'stable'],'moong'=>['supply_mt'=>1.7,'demand_mt'=>1.9,'balance'=>'-0.2 MT (Tight)','trend'=>'bullish']]],'live_agmarknet_feed'=>[['mandi'=>'Indore (MP)','crop'=>'Sharbati Wheat','modal_price'=>2780,'arrivals_tonnes'=>1420,'trend'=>'+₹35'],['mandi'=>'Khanna (Punjab)','crop'=>'Basmati Paddy','modal_price'=>3450,'arrivals_tonnes'=>2850,'trend'=>'+₹60'],['mandi'=>'Karnal (Haryana)','crop'=>'Wheat (PBW-502)','modal_price'=>2320,'arrivals_tonnes'=>3100,'trend'=>'0'],['mandi'=>'Akola (Maharashtra)','crop'=>'Desi Chana','modal_price'=>5450,'arrivals_tonnes'=>890,'trend'=>'+₹110'],['mandi'=>'Jaipur (Rajasthan)','crop'=>'Hybrid Bajra','modal_price'=>1980,'arrivals_tonnes'=>640,'trend'=>'-₹20'],['mandi'=>'Burdwan (Bengal)','crop'=>'Swarna Paddy','modal_price'=>2180,'arrivals_tonnes'=>1950,'trend'=>'+₹15']], 'live_imd_weather_alerts'=>[['region'=>'Vidarbha & Marathwada','alert_level'=>'ORANGE_RADAR','hazard'=>'Unseasonal Thunderstorms & 86% RH spike','action'=>'Seal aeration dampers on 18 outdoor godown bays'],['region'=>'Coastal Andhra & Odisha','alert_level'=>'YELLOW_RADAR','hazard'=>'Depression over Bay of Bengal; High moisture transit corridor','action'=>'Reroute truck dispatch inland via NH-16 avoid coastal fog'],['region'=>'Malwa Belt (MP)','alert_level'=>'GREEN_CLEAR','hazard'=>'Clear dry weather (32°C, 38% RH)','action'=>'Optimal window for deep silo aeration fan run (PID Cycle active)']]]];
    return [];
}
function scan_sample(string $key): array {
    $samples=[
    'wheat_high_moisture'=>['grain_type'=>'Wheat (Kalyan Sona)','batch_id'=>'AGR-IN-88921-WHT','location'=>'Indore Mandi Terminal Gate #4','source_farmer'=>'Kisan Samiti Cooperative #42','broken_pct'=>4.8,'discolored_pct'=>7.2,'insect_damage_count'=>3,'foreign_matter_pct'=>1.4,'estimated_moisture'=>15.9,'safe_moisture_limit'=>13,'quality_grade'=>'Grade B (Immediate Milling Required)','first_mile_warning'=>'HIGH MOISTURE DETECTED: Do NOT bag in airtight HDPE/Jute bags. High rot risk in transport corridor within 72 hours.','respiration_rate'=>'High (Thermal heating in progress: 33.8°C)','days_to_spoilage'=>4,'recommended_action'=>'Auto-generate Work Order for mobile grain dryer aeration, or direct dispatch to Indore Flour Mill (18 km).','confidence_score'=>97.4,'detection_boxes'=>[['label'=>'High Moisture Cluster','box'=>[25,30,45,60],'color'=>'#f59e0b'],['label'=>'Discolored / Spoilage Front','box'=>[60,40,85,75],'color'=>'#ef4444']]],
    'rice_weevil'=>['grain_type'=>'Paddy / Rice (Parmal 1509)','batch_id'=>'AGR-IN-44219-RIC','location'=>'Karnal Grain Hub - Godown Bay 3','source_farmer'=>'Ravi Shankar & FPO Assandh','broken_pct'=>8.4,'discolored_pct'=>5.1,'insect_damage_count'=>14,'foreign_matter_pct'=>2.2,'estimated_moisture'=>14.6,'safe_moisture_limit'=>13.5,'quality_grade'=>'Grade C (Secondary Processing / Cattle Feed)','first_mile_warning'=>'ACTIVE WEEVIL INFESTATION: Sitophilus oryzae detected in sample core. Immediate phosphine hermetic fumigation required.','respiration_rate'=>'Critical (Intergranular insect heat generated)','days_to_spoilage'=>2,'recommended_action'=>'Isolate batch from adjacent storage bays. Dispatch to Amul Cattle Feed Processing Unit (42 km).','confidence_score'=>98.6],
    'chana_grade_a'=>['grain_type'=>'Chickpea / Chana (Desi Bold)','batch_id'=>'AGR-IN-66302-CHN','location'=>'Akola APMC Yard - Warehouse #12','source_farmer'=>'Vidarbha Pulses Alliance','broken_pct'=>.9,'discolored_pct'=>1.2,'insect_damage_count'=>0,'foreign_matter_pct'=>.3,'estimated_moisture'=>10.4,'safe_moisture_limit'=>12,'quality_grade'=>'Grade A (Premium Buffer Stock / Export)','first_mile_warning'=>'EXCELLENT QUALITY: Zero insect damage detected. Low moisture profile ensures multi-season shelf life.','respiration_rate'=>'Dormant (Optimal preservation state)','days_to_spoilage'=>180,'recommended_action'=>'Approved for long-term buffer silo storage or direct high-premium mandi auction.','confidence_score'=>99.2],
    'bajra_mold'=>['grain_type'=>'Pearl Millet / Bajra (Hybrid RHB)','batch_id'=>'AGR-IN-19284-BJR','location'=>'Jaipur Agricultural Terminal','source_farmer'=>'Marwar Millets Collective','broken_pct'=>3.2,'discolored_pct'=>11.8,'insect_damage_count'=>6,'foreign_matter_pct'=>3.1,'estimated_moisture'=>16.4,'safe_moisture_limit'=>12.5,'quality_grade'=>'Grade C (Industrial Ethanol Conversion)','first_mile_warning'=>'MOLD BIOMARKERS DETECTED: Ergot/Claviceps fungal risk detected under NIR spectrum. Spoilage countdown active.','respiration_rate'=>'Very High (Microbial heat plume: 36.2°C)','days_to_spoilage'=>3,'recommended_action'=>'Divert immediately to Bio-Ethanol Distillery (64 km) to salvage 82% financial recovery.','confidence_score'=>96.8]];
    return $samples[$key]??$samples['wheat_high_moisture'];
}
function forecast(array $p): array {
    $crop=strtolower(trim((string)($p['grain_type']??'wheat')));$rates=['wheat'=>22750,'rice'=>24500,'moong'=>78000,'chana'=>54000,'bajra'=>19500,'jowar'=>29000];$base=['wheat'=>360,'rice'=>300,'moong'=>240,'chana'=>270,'bajra'=>210,'jowar'=>240];
    $stock=(float)($p['current_stock_tonnes']??5000)?:5000;$moist=(float)($p['moisture_pct']??12.5)?:12.5;$temp=(float)($p['temp_c']??27.5)?:27.5;$safe=in_array($crop,['moong','chana'],true)?12:13;$facility=(string)($p['facility_type']??'Modern Steel Silo');
    $allow=max(12,round(($base[$crop]??280)*pow(2,($safe-$moist)/1.7)*pow(2,(22-$temp)/6.5)*(strpos($facility,'Silo')!==false?1.15:(strpos($facility,'Godown')!==false?1:.78))));
    $now=strtotime('2026-09-17');$arrival=strtotime((string)($p['stock_arrival_date']??'2026-08-01'));if(!$arrival)$arrival=$now-35*86400;$days=max(1,round(($now-$arrival)/86400));$dts=round($allow-$days);$breach=date('Y-m-d',$now+$dts*86400);
    if($dts<=0){$window='ACTIVE_BREACH';$badge='🚨 ACTIVE SPOILAGE';$color='#ef4444';$severity='CRITICAL';}elseif($dts<=30){$window='BREACH_WITHIN_30D';$badge='🚨 URGENT (<30d)';$color='#f43f5e';$severity='CRITICAL';}elseif($dts<=60){$window='BREACH_WITHIN_60D';$badge='⚠️ 2-MONTH HAZARD (<60d)';$color='#f59e0b';$severity='HIGH';}else{$window='SAFE_BUFFER';$badge='🛡️ SAFE (>90d)';$color='#10b981';$severity='LOW';}
    $timeline=[];foreach([0,15,30,45,60] as $o){$age=$days+$o;$ratio=$age/$allow;$spoiled=($o>=$dts||$dts<=0)?min($stock,round($stock*(.12+.88*pow(max(0,$o-max(0,$dts))/45,1.25)))):0;$loss=$spoiled*($rates[$crop]??23000);$timeline[]=['day_offset'=>$o,'date'=>date('Y-m-d',$now+$o*86400),'label'=>$o?'Day +'.$o:'Today (Day 0)','storage_age_days'=>$age,'dml_pct'=>min(4.5,round(.5*pow($ratio,2.1),2)),'spoilage_risk_pct'=>min(100,max(1,round(100/(1+exp(-7.5*($ratio-.95)))))),'spoiled_tonnes'=>$spoiled,'loss_rupees'=>$loss,'loss_lakhs'=>round($loss/100000,1),'loss_cr'=>round($loss/10000000,2),'biological_state'=>$o<$dts-15?'Stable intergranular ERH; microbial respiration dormant.':'Thermal respiration rising; early fungal hyphae expansion.'];}
    $day60=$timeline[4];$cut=date('Y-m-d',$now+max(3,$dts-8)*86400);
    return ['unit_id'=>$p['unit_id']??null,'facility_name'=>$p['name']??'Regional Silo Facility','location'=>$p['location']??'India','grain_type'=>$crop,'current_stock_tonnes'=>$stock,'moisture_pct'=>$moist,'temp_c'=>$temp,'facility_type'=>$facility,'stock_arrival_date'=>date('Y-m-d',$arrival),'days_in_storage'=>$days,'total_safe_storage_days'=>$allow,'days_to_spoilage_breach'=>$dts,'breach_date'=>$breach,'window_status'=>$window,'status_badge'=>$badge,'status_color'=>$color,'severity'=>$severity,'urgency_headline'=>"Spoilage threshold breach projected in $dts days ($breach).",'wastage_at_60_days_tonnes'=>$day60['spoiled_tonnes'],'wastage_at_60_days_pct'=>round($day60['spoiled_tonnes']/$stock*100),'rupees_loss_at_60_days_cr'=>$day60['loss_cr'],'timeline'=>$timeline,'salvage_plan'=>['salvage_feasible'=>$dts>5||$days<$allow,'salvage_deadline_date'=>$cut,'days_to_execute_salvage'=>max(1,$dts-8),'primary_preservation_action'=>$moist>13.5?'Emergency Nocturnal Aeration (5.5 hrs/night @ <65% ambient RH)':'Preventive Turning & Inter-Chamber Recirculation','target_moisture_extraction'=>max(.5,round($moist-$safe,1)).'% reduction needed','liquidation_recommendation'=>$dts<=60?'Allocate '.number_format($stock).' T to regional dal/flour millers before '.$cut.' to recover inventory.':'Stock stable for strategic national buffer reserve. No urgent market offloading required.']];
}
